---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: 04-2. Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to main
  pull_request:
    branches: [main]
  workflow_call:

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    
    # Add explicit permissions
    permissions:
      contents: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Enable debug mode for troubleshooting
          LOG_LEVEL: INFO
          
          # Disable problematic linters that often cause failures
          VALIDATE_JSCPD: false                    # Disable copy-paste detection
          VALIDATE_CHECKOV: false                  # Disable Checkov security scanning
          VALIDATE_NATURAL_LANGUAGE: false        # Disable natural language linting
          VALIDATE_CSS: false                      # Disable CSS linting (often too strict)
          VALIDATE_HTML: false                     # Disable HTML linting
          VALIDATE_JAVASCRIPT_STANDARD: false     # Use ESLint instead
          VALIDATE_TYPESCRIPT_STANDARD: false     # Use ESLint instead
          VALIDATE_TERRAFORM_TERRASCAN: false     # Disable Terraform security scanning
          VALIDATE_KUBERNETES_KUBECONFORM: false  # Disable Kubernetes validation
          
          # Enable only essential linters
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_BASH: true
          
          # Configure linter behavior
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          YAML_CONFIG_FILE: .yamllint.yml
          
          # Ignore certain files/directories
          FILTER_REGEX_EXCLUDE: '.*/(node_modules|\.git|\.github/workflows)/.*'
